kind: Service
apiVersion: v1
metadata:
  name: fund-app-service
  labels:
    app: tomcat
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: fund-app
  ports:
    - port: 80
      targetPort: 8080